services:
    pxe-container:
        build: .
        stdin_open: true
        tty: true
        privileged: true
        network_mode: host
        cap_add:
            - SYS_ADMIN
        volumes:
            - ${PWD}/samba:/etc/samba
            - ${PWD}/RPi-PXE-Server:/app/RPi-PXE-Server
            - ${PWD}/srv:/srv
            - ${PWD}/media:/media/
            - /boot:/boot
            - /var/lib/nfs:/var/lib/nfs
        container_name: pxe-container
        image: pxe-image

